// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrentonDarts.Web.Data;

#nullable disable

namespace TrentonDarts.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509030139_AddNavGroupsAndItems")]
    partial class AddNavGroupsAndItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.BoardMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("EndSeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("endSeasonId");

                    b.Property<string>("EndingSeason")
                        .HasColumnType("text")
                        .HasColumnName("endingSeason");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer")
                        .HasColumnName("leagueId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<int?>("StartSeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("startSeasonId");

                    b.Property<string>("StartingSeason")
                        .HasColumnType("text")
                        .HasColumnName("startingSeason");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.ToTable("board_members", (string)null);
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.BrowsableFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FileName")
                        .HasColumnType("text")
                        .HasColumnName("fileName");

                    b.Property<string>("MimeType")
                        .HasColumnType("text")
                        .HasColumnName("mimeType");

                    b.Property<string>("RelativePath")
                        .HasColumnType("text")
                        .HasColumnName("relativePath");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("browsable_files", (string)null);
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.DartEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .HasColumnType("text")
                        .HasColumnName("address1");

                    b.Property<string>("Address2")
                        .HasColumnType("text")
                        .HasColumnName("address2");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DartStart")
                        .HasColumnType("text")
                        .HasColumnName("dartStart");

                    b.Property<string>("DartType")
                        .HasColumnType("text")
                        .HasColumnName("dartType");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EventContact")
                        .HasColumnType("text")
                        .HasColumnName("eventContact");

                    b.Property<string>("EventContact2")
                        .HasColumnType("text")
                        .HasColumnName("eventContact2");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eventDate");

                    b.Property<DateTime?>("EventEndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eventEndDate");

                    b.Property<int?>("EventTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("eventTypeId");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("text")
                        .HasColumnName("facebookUrl");

                    b.Property<string>("HostName")
                        .HasColumnType("text")
                        .HasColumnName("hostName");

                    b.Property<string>("HostPhone")
                        .HasColumnType("text")
                        .HasColumnName("hostPhone");

                    b.Property<string>("HostUrl")
                        .HasColumnType("text")
                        .HasColumnName("hostUrl");

                    b.Property<int?>("ImageFileId")
                        .HasColumnType("integer")
                        .HasColumnName("imageFileId");

                    b.Property<bool?>("IsTitleEvent")
                        .HasColumnType("boolean")
                        .HasColumnName("isTitleEvent");

                    b.Property<string>("LocationName")
                        .HasColumnType("text")
                        .HasColumnName("locationName");

                    b.Property<string>("MapUrl")
                        .HasColumnType("text")
                        .HasColumnName("mapUrl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PosterFile")
                        .HasColumnType("text")
                        .HasColumnName("posterFile");

                    b.Property<int?>("PosterFileId")
                        .HasColumnType("integer")
                        .HasColumnName("posterFileId");

                    b.Property<string>("RegistrationEndTime")
                        .HasColumnType("text")
                        .HasColumnName("registrationEndTime");

                    b.Property<string>("RegistrationStartTime")
                        .HasColumnType("text")
                        .HasColumnName("registrationStartTime");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<string>("Zip")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("dart_events", (string)null);
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.DartEventResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("eventId");

                    b.Property<string>("Finished")
                        .HasColumnType("text");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("orderId");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("playerId");

                    b.Property<string>("SpecificEventName")
                        .HasColumnType("text")
                        .HasColumnName("specificEventName");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("PlayerId");

                    b.ToTable("dart_event_results", (string)null);
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.MatchType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("match_types", (string)null);
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.MatchTypeGameRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BestOfNumberOfLegs")
                        .HasColumnType("integer")
                        .HasColumnName("bestOfNumberOfLegs");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DoubleIn")
                        .HasColumnType("boolean")
                        .HasColumnName("doubleIn");

                    b.Property<bool>("DoubleOut")
                        .HasColumnType("boolean")
                        .HasColumnName("doubleOut");

                    b.Property<bool>("ForfeitIfNoPlayers")
                        .HasColumnType("boolean")
                        .HasColumnName("forfeitIfNoPlayers");

                    b.Property<int>("GamePointValue")
                        .HasColumnType("integer")
                        .HasColumnName("gamePointValue");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gameType");

                    b.Property<string>("GroupName")
                        .HasColumnType("text")
                        .HasColumnName("groupName");

                    b.Property<int?>("LegPointValue")
                        .HasColumnType("integer")
                        .HasColumnName("legPointValue");

                    b.Property<int>("MatchTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("matchTypeId");

                    b.Property<int>("NumberOfLegs")
                        .HasColumnType("integer")
                        .HasColumnName("numberOfLegs");

                    b.Property<int>("NumberOfPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("numberOfPlayers");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("orderId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WhoStarts")
                        .HasColumnType("text")
                        .HasColumnName("whoStarts");

                    b.HasKey("Id");

                    b.HasIndex("MatchTypeId");

                    b.ToTable("match_type_game_rules", (string)null);
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.NavGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("nav_groups", (string)null);
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.NavGroupItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BrowsableFileId")
                        .HasColumnType("integer")
                        .HasColumnName("BrowsableFileId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsHeader")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSeparator")
                        .HasColumnType("boolean");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer");

                    b.Property<int>("NavGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("NavGroupId");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UrlTemplate")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BrowsableFileId");

                    b.HasIndex("NavGroupId");

                    b.ToTable("nav_group_items", (string)null);
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.PagePart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Html")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("page_parts", (string)null);
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AcceptEmail")
                        .HasColumnType("boolean")
                        .HasColumnName("acceptEmail");

                    b.Property<bool>("AcceptText")
                        .HasColumnType("boolean")
                        .HasColumnName("acceptText");

                    b.Property<string>("Address1")
                        .HasColumnType("text")
                        .HasColumnName("address1");

                    b.Property<string>("Address2")
                        .HasColumnType("text")
                        .HasColumnName("address2");

                    b.Property<string>("CellPhone")
                        .HasColumnType("text")
                        .HasColumnName("cellPhone");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstName");

                    b.Property<string>("HomePhone")
                        .HasColumnType("text")
                        .HasColumnName("homePhone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastName");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer")
                        .HasColumnName("leagueId");

                    b.Property<string>("Nickname")
                        .HasColumnType("text")
                        .HasColumnName("nickname");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("ShirtSize")
                        .HasColumnType("text")
                        .HasColumnName("shirtSize");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.Property<string>("Zip")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.Sponsor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .HasColumnType("text")
                        .HasColumnName("address1");

                    b.Property<string>("Address2")
                        .HasColumnType("text")
                        .HasColumnName("address2");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<string>("ContactName")
                        .HasColumnType("text")
                        .HasColumnName("contactName");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("text")
                        .HasColumnName("facebookUrl");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer")
                        .HasColumnName("leagueId");

                    b.Property<string>("MapUrl")
                        .HasColumnType("text")
                        .HasColumnName("mapUrl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<string>("Zip")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("sponsors", (string)null);
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer")
                        .HasColumnName("leagueId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("SponsorId")
                        .HasColumnType("integer")
                        .HasColumnName("sponsorId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SponsorId");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.WinterGameAward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AwardType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("awardType");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("gameId");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("playerId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("winter_game_awards", (string)null);
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.WinterGameResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AwayPlayers")
                        .HasColumnType("text")
                        .HasColumnName("awayPlayers");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ForfeitedBy")
                        .HasColumnType("text")
                        .HasColumnName("forfeitedBy");

                    b.Property<int>("GameRuleId")
                        .HasColumnType("integer")
                        .HasColumnName("gameRuleId");

                    b.Property<string>("HomePlayers")
                        .HasColumnType("text")
                        .HasColumnName("homePlayers");

                    b.Property<string>("Legs")
                        .HasColumnType("text");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("matchId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GameRuleId");

                    b.HasIndex("MatchId");

                    b.ToTable("winter_game_results", (string)null);
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.WinterMatchResult", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayScoreOverride")
                        .HasColumnType("integer")
                        .HasColumnName("awayScoreOverride");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("HasScorecard")
                        .HasColumnType("boolean")
                        .HasColumnName("hasScorecard");

                    b.Property<int?>("HomeScoreOverride")
                        .HasColumnType("integer")
                        .HasColumnName("homeScoreOverride");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("winter_match_results", (string)null);
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.WinterSeason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AccumulatePointsForAllParts")
                        .HasColumnType("boolean")
                        .HasColumnName("accumulatePointsForAllParts");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DefaultMatchTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("defaultMatchTypeId");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("EndYear")
                        .HasColumnType("integer")
                        .HasColumnName("endYear");

                    b.Property<int>("HalfPoints")
                        .HasColumnType("integer")
                        .HasColumnName("halfPoints");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("isCurrent");

                    b.Property<bool>("IsUsingMatchPoints")
                        .HasColumnType("boolean")
                        .HasColumnName("isUsingMatchPoints");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer")
                        .HasColumnName("leagueId");

                    b.Property<int>("MinPointForHalfPoints")
                        .HasColumnType("integer")
                        .HasColumnName("minPointForHalfPoints");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("SeasonType")
                        .HasColumnType("text")
                        .HasColumnName("seasonType");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer")
                        .HasColumnName("startYear");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("WinPoints")
                        .HasColumnType("integer")
                        .HasColumnName("winPoints");

                    b.HasKey("Id");

                    b.ToTable("winter_seasons", (string)null);
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.WinterSeasonMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("awayTeamId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Division")
                        .HasColumnType("text");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("homeTeamId");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer")
                        .HasColumnName("leagueId");

                    b.Property<int>("MatchTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("matchTypeId");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("seasonId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("WeekId")
                        .HasColumnType("integer")
                        .HasColumnName("weekId");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("MatchTypeId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("WeekId");

                    b.ToTable("winter_season_matches", (string)null);
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.WinterSeasonPlayerPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("text")
                        .HasColumnName("paymentStatus");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("playerId");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("seasonId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("winter_season_player_payments", (string)null);
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.WinterSeasonTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer")
                        .HasColumnName("leagueId");

                    b.Property<string>("PreSeasonDiv")
                        .HasColumnType("text")
                        .HasColumnName("preSeasonDiv");

                    b.Property<string>("RegularSeasonDiv")
                        .HasColumnType("text")
                        .HasColumnName("regularSeasonDiv");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("seasonId");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("teamId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TeamId");

                    b.ToTable("winter_season_teams", (string)null);
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.WinterSeasonTeamPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("text")
                        .HasColumnName("paymentStatus");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("seasonId");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("teamId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("winter_season_team_payments", (string)null);
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.WinterSeasonTeamPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer")
                        .HasColumnName("leagueId");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("playerId");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("seasonId");

                    b.Property<int>("SeasonTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("seasonTeamId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("SeasonTeamId");

                    b.ToTable("winter_season_team_players", (string)null);
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.WinterSeasonWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer")
                        .HasColumnName("leagueId");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("seasonId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WeekType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("weekType");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("winter_season_weeks", (string)null);
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.WinterStatAward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AwardId")
                        .HasColumnType("integer")
                        .HasColumnName("awardId");

                    b.Property<string>("AwardType")
                        .HasColumnType("text")
                        .HasColumnName("awardType");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Division")
                        .HasColumnType("text");

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("gameId");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("matchId");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("playerId");

                    b.Property<string>("PlayerName")
                        .HasColumnType("text")
                        .HasColumnName("playerName");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("seasonId");

                    b.Property<string>("SeasonPart")
                        .HasColumnType("text")
                        .HasColumnName("seasonPart");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("teamId");

                    b.Property<string>("TeamName")
                        .HasColumnType("text")
                        .HasColumnName("teamName");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("winter_stats_awards", (string)null);
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.WinterStatMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Division")
                        .HasColumnType("text");

                    b.Property<bool>("HasScorecard")
                        .HasColumnType("boolean")
                        .HasColumnName("hasScorecard");

                    b.Property<bool>("HomeMatch")
                        .HasColumnType("boolean")
                        .HasColumnName("homeMatch");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("matchId");

                    b.Property<int>("MatchPoints")
                        .HasColumnType("integer")
                        .HasColumnName("matchPoints");

                    b.Property<int>("PointsLost")
                        .HasColumnType("integer")
                        .HasColumnName("pointsLost");

                    b.Property<int>("PointsWon")
                        .HasColumnType("integer")
                        .HasColumnName("pointsWon");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("seasonId");

                    b.Property<string>("SeasonPart")
                        .HasColumnType("text")
                        .HasColumnName("seasonPart");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("teamId");

                    b.Property<string>("TeamName")
                        .HasColumnType("text")
                        .HasColumnName("teamName");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("winter_stats_matches", (string)null);
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.WinterStatPlayerGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Division")
                        .HasColumnType("text");

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("gameId");

                    b.Property<int>("GameNumber")
                        .HasColumnType("integer")
                        .HasColumnName("gameNumber");

                    b.Property<string>("GameType")
                        .HasColumnType("text")
                        .HasColumnName("gameType");

                    b.Property<bool>("IsForfeit")
                        .HasColumnType("boolean")
                        .HasColumnName("isForfeit");

                    b.Property<bool>("IsHome")
                        .HasColumnType("boolean")
                        .HasColumnName("isHome");

                    b.Property<bool>("IsWon")
                        .HasColumnType("boolean")
                        .HasColumnName("isWon");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("matchId");

                    b.Property<int>("NumberOfPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("numberOfPlayers");

                    b.Property<int>("NumberOfPoints")
                        .HasColumnType("integer")
                        .HasColumnName("numberOfPoints");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("playerId");

                    b.Property<string>("PlayerName")
                        .HasColumnType("text")
                        .HasColumnName("playerName");

                    b.Property<int>("PlayerPosition")
                        .HasColumnType("integer")
                        .HasColumnName("playerPosition");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("seasonId");

                    b.Property<string>("SeasonPart")
                        .HasColumnType("text")
                        .HasColumnName("seasonPart");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("teamId");

                    b.Property<string>("TeamName")
                        .HasColumnType("text")
                        .HasColumnName("teamName");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("winter_stats_player_games", (string)null);
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.WinterStatTeamGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Division")
                        .HasColumnType("text");

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("gameId");

                    b.Property<string>("GameType")
                        .HasColumnType("text")
                        .HasColumnName("gameType");

                    b.Property<bool>("IsForfeitGame")
                        .HasColumnType("boolean")
                        .HasColumnName("isForfeitGame");

                    b.Property<bool>("IsWon")
                        .HasColumnType("boolean")
                        .HasColumnName("isWon");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("matchId");

                    b.Property<int>("NumberOfPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("numberOfPlayers");

                    b.Property<int>("NumberOfPoints")
                        .HasColumnType("integer")
                        .HasColumnName("numberOfPoints");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("seasonId");

                    b.Property<string>("SeasonPart")
                        .HasColumnType("text")
                        .HasColumnName("seasonPart");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("teamId");

                    b.Property<string>("TeamName")
                        .HasColumnType("text")
                        .HasColumnName("teamName");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("winter_stats_team_games", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TrentonDarts.Web.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TrentonDarts.Web.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrentonDarts.Web.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TrentonDarts.Web.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.DartEventResult", b =>
                {
                    b.HasOne("TrentonDarts.Web.Data.Entities.DartEvent", "Event")
                        .WithMany("Results")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrentonDarts.Web.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.Navigation("Event");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.MatchTypeGameRule", b =>
                {
                    b.HasOne("TrentonDarts.Web.Data.Entities.MatchType", "MatchType")
                        .WithMany("GameRules")
                        .HasForeignKey("MatchTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchType");
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.NavGroupItem", b =>
                {
                    b.HasOne("TrentonDarts.Web.Data.Entities.BrowsableFile", "BrowsableFile")
                        .WithMany()
                        .HasForeignKey("BrowsableFileId");

                    b.HasOne("TrentonDarts.Web.Data.Entities.NavGroup", "NavGroup")
                        .WithMany("Items")
                        .HasForeignKey("NavGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrowsableFile");

                    b.Navigation("NavGroup");
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.Team", b =>
                {
                    b.HasOne("TrentonDarts.Web.Data.Entities.Sponsor", "Sponsor")
                        .WithMany("Teams")
                        .HasForeignKey("SponsorId");

                    b.Navigation("Sponsor");
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.WinterGameAward", b =>
                {
                    b.HasOne("TrentonDarts.Web.Data.Entities.WinterGameResult", "GameResult")
                        .WithMany("Awards")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrentonDarts.Web.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameResult");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.WinterGameResult", b =>
                {
                    b.HasOne("TrentonDarts.Web.Data.Entities.MatchTypeGameRule", "GameRule")
                        .WithMany()
                        .HasForeignKey("GameRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrentonDarts.Web.Data.Entities.WinterMatchResult", "MatchResult")
                        .WithMany("GameResults")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameRule");

                    b.Navigation("MatchResult");
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.WinterMatchResult", b =>
                {
                    b.HasOne("TrentonDarts.Web.Data.Entities.WinterSeasonMatch", "Match")
                        .WithOne("MatchResult")
                        .HasForeignKey("TrentonDarts.Web.Data.Entities.WinterMatchResult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.WinterSeasonMatch", b =>
                {
                    b.HasOne("TrentonDarts.Web.Data.Entities.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrentonDarts.Web.Data.Entities.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrentonDarts.Web.Data.Entities.MatchType", "MatchType")
                        .WithMany()
                        .HasForeignKey("MatchTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrentonDarts.Web.Data.Entities.WinterSeason", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrentonDarts.Web.Data.Entities.WinterSeasonWeek", "Week")
                        .WithMany("Matches")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("MatchType");

                    b.Navigation("Season");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.WinterSeasonTeam", b =>
                {
                    b.HasOne("TrentonDarts.Web.Data.Entities.WinterSeason", "Season")
                        .WithMany("SeasonTeams")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrentonDarts.Web.Data.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.WinterSeasonTeamPlayer", b =>
                {
                    b.HasOne("TrentonDarts.Web.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrentonDarts.Web.Data.Entities.WinterSeason", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrentonDarts.Web.Data.Entities.WinterSeasonTeam", "SeasonTeam")
                        .WithMany("TeamPlayers")
                        .HasForeignKey("SeasonTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Season");

                    b.Navigation("SeasonTeam");
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.WinterSeasonWeek", b =>
                {
                    b.HasOne("TrentonDarts.Web.Data.Entities.WinterSeason", "Season")
                        .WithMany("Weeks")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.DartEvent", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.MatchType", b =>
                {
                    b.Navigation("GameRules");
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.NavGroup", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.Sponsor", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.WinterGameResult", b =>
                {
                    b.Navigation("Awards");
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.WinterMatchResult", b =>
                {
                    b.Navigation("GameResults");
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.WinterSeason", b =>
                {
                    b.Navigation("SeasonTeams");

                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.WinterSeasonMatch", b =>
                {
                    b.Navigation("MatchResult");
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.WinterSeasonTeam", b =>
                {
                    b.Navigation("TeamPlayers");
                });

            modelBuilder.Entity("TrentonDarts.Web.Data.Entities.WinterSeasonWeek", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
